version: '3.8'

services:
  automation_quotation-5tech_lark_kiotviet_automation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automation_quotation-5tech_lark_kiotviet_automation
    ports:
      - "3003:8088"
    networks:
      - automation_network
    restart: unless-stopped

networks:
  automation_network:
    driver: bridge
